<x-app-layout title="Dashboard">
    <x-page-title title="Operational overview" eyebrow="Workspace" description="A clear view of access, activity, and platform readiness.">@can('users.create')<x-button href="{{ route('administration.create','users') }}">Add user</x-button>@endcan</x-page-title>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach($metrics as $metric)<article class="app-panel relative overflow-hidden p-5"><span class="absolute inset-y-0 left-0 w-1 bg-accent"></span><div class="flex items-start justify-between"><p class="text-xs font-medium uppercase tracking-wider text-slate-500">{{ $metric['label'] }}</p><span class="h-2.5 w-2.5 rounded-full bg-{{ $metric['tone'] }}-500"></span></div><p class="mt-3 text-3xl font-semibold tabular-nums text-primary dark:text-white">{{ $metric['value'] }}</p><p class="mt-1 text-xs font-normal text-slate-500">{{ $metric['note'] }}</p></article>@endforeach
    </div>
    <div class="mt-6 grid gap-6 xl:grid-cols-[1.65fr_1fr]">
        <x-card title="Activity overview" subtitle="System events over the last seven days"><div class="h-64"><canvas id="activity-chart" aria-label="System activity for the last seven days" role="img"></canvas></div></x-card>
        <x-card title="System status" subtitle="Live service indicators"><div class="divide-y divide-slate-100 dark:divide-slate-800">@foreach(['Application'=>'Operational','Database'=>'Connected','Queue'=>'Running','Mail'=>'Configured'] as $service=>$status)<div class="flex items-center py-3"><span class="mr-3 h-2 w-2 rounded-full bg-emerald-500"></span><span class="text-sm font-medium">{{ $service }}</span><span class="ml-auto text-xs text-slate-500">{{ $status }}</span></div>@endforeach</div></x-card>
        <x-card title="Recent activity" subtitle="Latest security and account events"><div class="divide-y divide-slate-100 dark:divide-slate-800">@foreach([['User account created','System administrator','2 min ago'],['Role permissions reviewed','Access manager','42 min ago'],['Application settings updated','System administrator','3 hours ago']] as $event)<div class="flex gap-3 py-3"><span class="mt-1 h-7 w-1 bg-primary"></span><div><p class="text-sm font-medium">{{ $event[0] }}</p><p class="text-xs text-slate-500">{{ $event[1] }} · {{ $event[2] }}</p></div></div>@endforeach</div></x-card>
        <x-card title="Quick actions" subtitle="Common workspace tasks"><div class="grid grid-cols-2 gap-3">@can('users.create')<x-button variant="secondary" href="{{ route('administration.create','users') }}">Create user</x-button>@endcan @can('roles.manage')<x-button variant="secondary" href="{{ route('administration.create','roles') }}">Define role</x-button>@endcan @can('audit-logs.view')<x-button variant="secondary" href="{{ route('system.audit') }}">Review logs</x-button>@endcan @can('settings.manage')<x-button variant="secondary" href="{{ route('system.settings') }}">Settings</x-button>@endcan</div></x-card>
    </div>
</x-app-layout>
