@php
    $appVersion = config('app.version', '1.0.0');
    $systemInfo = [
        ['label' => 'Framework', 'value' => 'Laravel '.app()->version()],
        ['label' => 'Runtime', 'value' => 'PHP '.PHP_VERSION],
        ['label' => 'Environment', 'value' => ucfirst(app()->environment())],
        ['label' => 'Release', 'value' => 'v'.$appVersion],
        ['label' => 'Database', 'value' => strtoupper(config('database.default'))],
    ];
    $capabilities = [
        ['Authentication', 'Secure registration, login, password recovery, and email verification.', 'M12 3l7 4v5c0 4.4-3 7.7-7 9-4-1.3-7-4.6-7-9V7l7-4zm0 5v4m0 4h.01'],
        ['User Management', 'A complete foundation for managing user accounts, profiles, and access.', 'M16 21v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2m7-10a4 4 0 100-8 4 4 0 000 8zm5 0v-2a4 4 0 00-3-3.87'],
        ['Roles & Permissions', 'Fine-grained authorization built on proven role and permission patterns.', 'M9 12l2 2 4-4m6-4a12 12 0 01-9 15 12 12 0 01-9-15l9-4 9 4z'],
        ['System Settings', 'Centralized, extensible configuration for application-wide preferences.', 'M12 15.5a3.5 3.5 0 100-7 3.5 3.5 0 000 7zm7.4-3.5a7.4 7.4 0 00-.1-1l2-1.5-2-3.4-2.4 1'],
        ['Blade Components', 'Consistent interface components that accelerate polished product delivery.', 'M4 4h7v7H4V4zm9 0h7v7h-7V4zM4 13h7v7H4v-7zm9 0h7v7h-7v-7z'],
        ['Audit Logs', 'Traceable activity records that strengthen accountability and operations.', 'M9 5H6a2 2 0 00-2 2v12a2 2 0 002 2h12a2 2 0 002-2V7a2 2 0 00-2-2h-3m-6 0a3 3 0 016 0m-6 0h6m-7 5h8m-8 4h5'],
    ];
@endphp
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="scroll-smooth">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A production-ready Laravel foundation for secure, scalable business applications.">
    <title>Laravel Enterprise Boilerplate</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <style>
        [x-cloak]{display:none!important}b,strong{font-weight:600}.highlight{position:relative;z-index:0;color:#ff7f45}.highlight:after{content:"";position:absolute;z-index:-1;left:-.08em;right:-.08em;bottom:.05em;height:.34em;background:#ffe5d8}.dot-grid{background-image:radial-gradient(rgba(255,127,69,.35) 1px,transparent 1px);background-size:13px 13px}.chart-grid{background-image:linear-gradient(#e6ecec 1px,transparent 1px),linear-gradient(90deg,#e6ecec 1px,transparent 1px);background-size:36px 28px}.reveal{animation:reveal .65s ease-out both}.tech-marquee{position:relative;overflow:hidden}.tech-marquee:before,.tech-marquee:after{content:"";position:absolute;z-index:2;top:0;bottom:0;width:clamp(2rem,8vw,9rem);pointer-events:none}.tech-marquee:before{left:0;background:linear-gradient(90deg,#fff,rgba(255,255,255,0))}.tech-marquee:after{right:0;background:linear-gradient(270deg,#fff,rgba(255,255,255,0))}.tech-marquee__track{display:flex;width:max-content;animation:tech-marquee 28s linear infinite;will-change:transform}.tech-marquee:hover .tech-marquee__track,.tech-marquee:focus-within .tech-marquee__track{animation-play-state:paused}.tech-marquee__group{display:flex;min-width:100vw;flex-shrink:0;align-items:center;justify-content:space-around;gap:clamp(2.5rem,6vw,7rem);padding:0 clamp(2.5rem,6vw,7rem);white-space:nowrap}.tech-marquee__item{font-weight:500}@keyframes reveal{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:none}}@keyframes tech-marquee{to{transform:translateX(-50%)}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.reveal{animation:none}.tech-marquee__track{width:100%;animation:none;will-change:auto}.tech-marquee__group{width:100%;min-width:0;flex-wrap:wrap;justify-content:center;white-space:normal}.tech-marquee__group[aria-hidden="true"]{display:none}*{transition-duration:.01ms!important}}
    </style>
</head>
<body class="overflow-x-hidden bg-white font-sans text-[#083b40] antialiased">
<a href="#main" class="sr-only z-[100] bg-white px-4 py-3 font-medium focus:fixed focus:left-4 focus:top-4 focus:not-sr-only">Skip to content</a>
<header x-data="{open:false}" @keydown.escape.window="open=false" class="sticky top-0 z-50 bg-[#083b40] text-white shadow-lg">
    <nav class="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8" aria-label="Primary navigation">
        <a href="#home" class="flex items-center gap-2 text-xl font-semibold tracking-tight"><span class="grid h-8 w-8 place-items-center rounded-full border-2 border-[#ff7f45] text-[10px] text-[#ff7f45]">LE</span>Laravel Enterprise</a>
        <div class="hidden items-center gap-10 lg:flex">@foreach([['Home','#home'],['About','#about'],['Services','#services'],['Architecture','#architecture'],['Support','#support']] as [$label,$href])<a href="{{ $href }}" class="text-sm font-medium transition hover:text-[#ff7f45] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#ff7f45]">{{ $label }}</a>@endforeach</div>
        <div class="hidden items-center gap-3 lg:flex">@auth<a href="{{ route('dashboard') }}" class="rounded bg-[#ff7f45] px-6 py-3 text-sm font-semibold text-white hover:bg-[#f16f36]">Dashboard</a>@else<a href="{{ route('login') }}" class="rounded bg-[#ff7f45] px-6 py-3 text-sm font-semibold text-white hover:bg-[#f16f36]">Login</a>@endauth</div>
        <button @click="open=!open" :aria-expanded="open.toString()" aria-controls="mobile-nav" class="rounded p-2 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#ff7f45] lg:hidden"><span class="sr-only">Toggle menu</span><svg width="28" height="28" class="h-7 w-7" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path x-show="!open" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/><path x-show="open" x-cloak stroke-width="2" d="M6 6l12 12M18 6L6 18"/></svg></button>
    </nav>
    <div id="mobile-nav" x-show="open" x-cloak class="border-t border-white/10 px-5 py-5 lg:hidden"><div class="grid gap-4">@foreach([['Home','#home'],['About','#about'],['Services','#services'],['Architecture','#architecture'],['Support','#support']] as [$label,$href])<a @click="open=false" href="{{ $href }}" class="font-medium">{{ $label }}</a>@endforeach @auth<a href="{{ route('dashboard') }}" class="text-[#ff9d70]">Dashboard</a><a href="{{ route('profile.edit') }}">Profile</a><form method="POST" action="{{ route('logout') }}">@csrf<button class="font-medium">Log out</button></form>@else<a href="{{ route('login') }}" class="text-[#ff9d70]">Login</a>@endauth</div></div>
</header>
<main id="main">
<section id="home" class="scroll-mt-20 overflow-hidden bg-[#083b40] text-white"><div class="mx-auto grid min-h-[690px] max-w-7xl items-center gap-14 px-5 py-20 lg:grid-cols-2 lg:px-8">
    <div class="reveal"><p class="text-sm font-semibold tracking-wide"><span class="mr-3 text-[#ff7f45]">100%</span>Production-ready foundation</p><h1 class="mt-8 text-5xl font-semibold leading-[1.14] tracking-[-.04em] sm:text-6xl">Managing business <span class="highlight">systems</span> has never been easier.</h1><p class="mt-6 max-w-xl text-lg leading-8 text-[#9fb8ba]">Authentication, authorization, system tools, and modular architecture in one dependable Laravel foundation.</p><div class="mt-8 flex flex-wrap gap-3">@auth<a href="{{ route('dashboard') }}" class="bg-[#ff7f45] px-7 py-4 font-semibold hover:bg-[#f16f36]">Open dashboard →</a>@else<a href="{{ route('register') }}" class="bg-[#ff7f45] px-7 py-4 font-semibold hover:bg-[#f16f36]">Get started →</a><a href="{{ route('login') }}" class="border border-white/30 px-7 py-4 font-semibold hover:bg-white/10">Sign in</a>@endauth</div><div class="mt-7 flex flex-wrap gap-8 text-sm font-medium"><span>● <b class="text-[#ff7f45]">✓</b> MySQL ready</span><span>● <b class="text-[#ff7f45]">✓</b> Permission aware</span></div></div>
    <div class="relative min-h-[480px]" aria-hidden="true"><div class="dot-grid absolute inset-10 rounded-full opacity-50"></div><div class="absolute left-4 top-10 w-[88%] rotate-[-2deg] bg-white p-6 text-[#083b40] shadow-2xl sm:left-12"><div class="flex items-center justify-between border-b pb-5"><div><p class="text-xs font-medium uppercase tracking-widest text-slate-400">Operations overview</p><p class="mt-1 text-3xl font-semibold">Enterprise control</p></div><span class="rounded bg-[#d9eee7] px-3 py-2 text-xs font-semibold">LIVE</span></div><div class="mt-6 grid grid-cols-3 gap-3"><div class="bg-[#fff8f3] p-4"><b class="text-2xl">6</b><p class="text-xs text-slate-500">Core modules</p></div><div class="bg-[#fff8f3] p-4"><b class="text-2xl">8</b><p class="text-xs text-slate-500">Capabilities</p></div><div class="bg-[#fff8f3] p-4"><b class="text-2xl">3</b><p class="text-xs text-slate-500">Access layers</p></div></div><div class="chart-grid relative mt-6 h-48 overflow-hidden"><svg class="absolute inset-0 h-full w-full" viewBox="0 0 500 190" fill="none"><path d="M0 150C70 145 80 90 145 110S230 155 275 95s70-38 110-62 68 5 115-8" stroke="#ff7f45" stroke-width="6"/><path d="M0 165C55 148 90 155 130 130s80-14 120-45 75 30 120-2 80-20 130-48" stroke="#44b989" stroke-width="5"/></svg></div></div><div class="absolute right-0 top-2 bg-[#ff7f45] px-5 py-4 text-sm font-semibold shadow-xl">All systems operational</div><div class="absolute bottom-5 left-0 bg-white/95 px-5 py-4 text-sm text-[#083b40] shadow-xl"><b>Access review complete</b><br><span class="text-xs text-slate-500">Policies and permissions aligned</span></div></div>
</div></section>
<section class="tech-marquee border-b py-10" tabindex="0" aria-label="Technology stack">
    <div class="tech-marquee__track text-center text-lg text-slate-400">
        <ul class="tech-marquee__group" role="list">
            @foreach(['Laravel','MySQL','Tailwind','Alpine','Spatie','Vite'] as $tech)<li class="tech-marquee__item">{{ $tech }}</li>@endforeach
        </ul>
        <ul class="tech-marquee__group" role="list" aria-hidden="true">
            @foreach(['Laravel','MySQL','Tailwind','Alpine','Spatie','Vite'] as $tech)<li class="tech-marquee__item">{{ $tech }}</li>@endforeach
        </ul>
    </div>
</section>

<section id="services" class="scroll-mt-20 py-24"><div class="mx-auto max-w-7xl px-5 lg:px-8"><div class="grid gap-10 lg:grid-cols-2 lg:items-end"><div><p class="text-xs font-semibold uppercase tracking-[.18em] text-[#ff7f45]">Easy handling</p><h2 class="mt-5 text-4xl font-semibold leading-tight sm:text-5xl">Discover powerful features to boost <span class="highlight">delivery</span></h2></div><p class="max-w-lg text-lg leading-8 text-slate-600">A cohesive foundation for teams that need to ship secure, maintainable business applications faster.</p></div><div class="mt-16 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">@foreach($capabilities as [$title,$description,$path])<article class="group min-h-64 bg-[#fff8f3] p-8 shadow-[0_10px_20px_-16px_rgba(8,59,64,.45)] transition hover:-translate-y-2"><svg width="48" height="48" class="h-12 w-12 text-[#ff7f45]" fill="none" stroke="currentColor" stroke-width="1.7" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="{{ $path }}"/></svg><h3 class="mt-8 text-xl font-semibold">{{ $title }}</h3><p class="mt-4 text-sm leading-6 text-slate-600">{{ $description }}</p><span class="mt-6 block text-2xl transition group-hover:translate-x-2">→</span></article>@endforeach</div></div></section>

<section id="about" class="scroll-mt-20 bg-[#fff8f3] py-24"><div class="mx-auto grid max-w-7xl items-center gap-16 px-5 lg:grid-cols-2 lg:px-8"><div><p class="text-xs font-semibold uppercase tracking-[.18em] text-[#ff7f45]">Structure</p><h2 class="mt-5 text-4xl font-semibold sm:text-5xl">Discover all <span class="highlight">our foundations</span></h2><p class="mt-6 max-w-xl text-lg leading-8 text-slate-600">A stable shared platform establishes security, governance, and delivery standards while keeping business modules independent.</p><div class="mt-8 grid gap-5 sm:grid-cols-2">@foreach(['Stable application core','Modular boundaries','Centralized settings','Traceable operations'] as $item)<p class="font-medium"><span class="mr-3 text-[#ff7f45]">●</span>{{ $item }}</p>@endforeach</div><a href="#architecture" class="mt-10 inline-block bg-[#083b40] px-7 py-4 text-sm font-semibold text-white">Explore architecture</a></div><div class="relative min-h-[500px]" aria-hidden="true"><div class="absolute left-4 top-5 h-64 w-64 bg-[#d9eee7]"></div><div class="absolute bottom-3 right-0 h-64 w-64 border-2 border-[#44b989]"></div><div class="absolute inset-x-10 top-16 bg-white p-7 shadow-2xl sm:inset-x-20"><p class="text-sm text-slate-500">Platform readiness</p><p class="text-4xl font-semibold">98.6%</p><div class="chart-grid relative mt-6 h-56"><svg class="absolute inset-0 h-full w-full" viewBox="0 0 400 220" fill="none"><path d="M0 170L55 145l55 15 55-80 55 35 55-52 55 27 60-65" stroke="#44b989" stroke-width="5"/><path d="M0 185l70-20 60 10 75-30 70 22 125-55" stroke="#ff7f45" stroke-width="5"/></svg></div></div></div></div></section>

<section id="architecture" class="scroll-mt-20 py-24"><div class="mx-auto grid max-w-7xl items-center gap-16 px-5 lg:grid-cols-2 lg:px-8"><div class="relative min-h-[500px]" aria-hidden="true"><div class="absolute inset-8 rotate-6 bg-[#fff0e9]"></div><div class="absolute inset-10 -rotate-3 bg-[#effaf5]"></div><div class="absolute inset-x-14 top-4 bg-white p-8 shadow-2xl"><p class="text-sm text-slate-500">Foundation health</p><p class="mt-1 text-3xl font-semibold">Stable core</p><div class="mt-8 space-y-5">@foreach([['Authentication','100%'],['Authorization','100%'],['Settings','96%'],['Auditability','94%']] as [$label,$value])<div><div class="flex justify-between text-sm font-medium"><span>{{ $label }}</span><span>{{ $value }}</span></div><div class="mt-2 h-2 bg-slate-100"><div class="h-2 bg-[#ff7f45]" style="width:{{ $value }}"></div></div></div>@endforeach</div></div></div><div><p class="text-xs font-semibold uppercase tracking-[.18em] text-[#ff7f45]">Performance metrics</p><h2 class="mt-5 text-4xl font-semibold sm:text-5xl">Grow your business on a <span class="highlight">strong core</span></h2><p class="mt-6 text-lg leading-8 text-slate-600">Spend less time rebuilding infrastructure and more time refining workflows that create value.</p><div class="mt-8 grid grid-cols-2 gap-8"><div><b class="text-3xl">8</b><p class="text-sm text-slate-500">Reusable capabilities</p></div><div><b class="text-3xl">3</b><p class="text-sm text-slate-500">Authorization layers</p></div></div><ul class="mt-8 space-y-4">@foreach(['One consistent technical baseline','MySQL-first configuration','Independent module growth'] as $item)<li class="font-medium"><span class="mr-3 text-[#ff7f45]">●</span>{{ $item }}</li>@endforeach</ul></div></div></section>

<section class="bg-[#083b40] py-16 text-white"><div class="mx-auto grid max-w-7xl grid-cols-2 gap-10 px-5 text-center lg:grid-cols-4 lg:px-8">@foreach([['6','Core modules'],['8','Capabilities'],[strtoupper(config('database.default')),'Database'],['PHP '.PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION,'Runtime']] as [$number,$label])<div><span class="mx-auto grid h-16 w-16 place-items-center rounded bg-[#d9eee7] text-xl font-semibold text-[#083b40]">✓</span><p class="mt-6 text-3xl font-semibold">{{ $number }}</p><p class="mt-2 text-[#9fb8ba]">{{ $label }}</p></div>@endforeach</div></section>

<section class="bg-[#fff8f3] py-24"><div class="mx-auto max-w-7xl px-5 lg:px-8"><div class="text-center"><p class="text-xs font-semibold uppercase tracking-[.18em] text-[#ff7f45]">Adoption paths</p><h2 class="mx-auto mt-5 max-w-3xl text-4xl font-semibold sm:text-5xl">Choose the path that fits <span class="highlight">your business</span></h2></div><div class="mt-16 grid gap-6 lg:grid-cols-3">@foreach([['Starter foundation','Explore the proven core and understand its conventions.',['Authentication','Components','MySQL configuration']],['Production','Build production applications with governed access and operations.',['Roles and permissions','Settings','Audit logs']],['Enterprise extension','Extend the platform with independent business capabilities.',['Modular architecture','Custom policies','Team conventions']]] as [$title,$copy,$items])<article class="bg-white p-4 shadow-md"><div class="{{ $loop->iteration===2 ? 'bg-[#083b40] text-white' : 'bg-[#fff8f3]' }} p-7"><h3 class="text-2xl font-semibold">{{ $title }}</h3><p class="mt-4 leading-7 {{ $loop->iteration===2 ? 'text-[#bcd0d1]' : 'text-slate-600' }}">{{ $copy }}</p></div><ul class="space-y-5 p-7">@foreach($items as $item)<li><span class="mr-3 text-[#ff7f45]">✓</span>{{ $item }}</li>@endforeach</ul><div class="p-7 pt-0">@auth<a href="{{ route('dashboard') }}" class="block border border-[#083b40] px-5 py-3 text-center font-semibold hover:bg-[#083b40] hover:text-white">Open dashboard</a>@else<a href="{{ route('register') }}" class="block border border-[#083b40] px-5 py-3 text-center font-semibold hover:bg-[#083b40] hover:text-white">Get started</a>@endauth</div></article>@endforeach</div></div></section>

<section id="support" class="scroll-mt-20 py-24"><div class="mx-auto max-w-7xl px-5 lg:px-8"><div class="text-center"><p class="text-xs font-semibold uppercase tracking-[.18em] text-[#ff7f45]">Need support</p><h2 class="mt-5 text-4xl font-semibold sm:text-5xl">Frequently asked <span class="highlight">questions</span></h2></div><div class="mt-16 grid gap-x-20 gap-y-10 md:grid-cols-2">@foreach([['Does it use MySQL?','Yes. The boilerplate is configured for MySQL, including its isolated testing database.'],['Can I add business modules?','Yes. The stable core is designed to accept independent modules without duplicating shared infrastructure.'],['How is access controlled?','Policies, middleware, roles, and permissions work together for granular authorization.'],['Can I customize the interface?','Yes. Shared Blade components and Tailwind design tokens provide a consistent starting point.'],['Is runtime data real?','Yes. Framework, PHP, environment, release, and database values are read from the application.'],['Does it replace business logic?','No. It provides the foundation so your team can focus on business-specific workflows.']] as $question)<article class="grid grid-cols-[42px_1fr] gap-3"><span class="grid h-9 w-9 place-items-center rounded-full bg-[#d9eee7] font-semibold">{{ $loop->iteration }}</span><div><h3 class="text-lg font-semibold">{{ $question[0] }}</h3><p class="mt-3 leading-7 text-slate-600">{{ $question[1] }}</p></div></article>@endforeach</div></div></section>

<section class="bg-[#fff8f3] py-16"><div class="mx-auto grid max-w-7xl gap-5 px-5 md:grid-cols-3 lg:px-8">@foreach([['Platform','Laravel Enterprise foundation'],['Runtime','Laravel '.app()->version().' / PHP '.PHP_VERSION],['Database','Configured for '.strtoupper(config('database.default'))]] as [$label,$value])<div class="bg-white p-7 shadow-sm"><p class="text-xs font-semibold uppercase tracking-widest text-[#ff7f45]">{{ $label }}</p><p class="mt-2 font-semibold">{{ $value }}</p></div>@endforeach</div></section>
</main>
<footer class="bg-[#03282c] py-20 text-white"><div class="mx-auto grid max-w-7xl gap-12 px-5 md:grid-cols-2 lg:grid-cols-4 lg:px-8"><div><p class="text-xl font-semibold"><span class="text-[#ff7f45]">LE</span> Laravel Enterprise</p><p class="mt-5 max-w-xs leading-7 text-[#8eaaac]">A dependable foundation for secure, scalable business applications.</p><p class="mt-7 text-sm text-[#8eaaac]">© {{ date('Y') }} · v{{ $appVersion }}</p></div><div><h2 class="font-semibold">Navigate</h2><div class="mt-6 grid gap-3 text-sm text-[#8eaaac]"><a href="#home">Home</a><a href="#services">Services</a><a href="#architecture">Architecture</a><a href="#support">Support</a></div></div><div><h2 class="font-semibold">Platform</h2><dl class="mt-6 grid gap-3 text-sm text-[#8eaaac]">@foreach($systemInfo as $info)<div><dt class="inline">{{ $info['label'] }}:</dt> <dd class="inline text-white">{{ $info['value'] }}</dd></div>@endforeach</dl></div><div><h2 class="font-semibold">Ready to build?</h2><p class="mt-5 leading-7 text-[#8eaaac]">Begin with the core, then extend it around your business.</p>@auth<a href="{{ route('dashboard') }}" class="mt-7 inline-block bg-[#ff7f45] px-6 py-3 font-semibold">Dashboard →</a>@else<a href="{{ route('register') }}" class="mt-7 inline-block bg-[#ff7f45] px-6 py-3 font-semibold">Get started →</a>@endauth</div></div></footer>
</body></html>
